version: '3.9'

x-common: &common
  logging:
    options:
      max-size: "5m"
      max-file: "10"
  build:
    network: host
  restart: unless-stopped
  init: true
  network_mode: host

services:
  registry-proxy:
    <<: *common
    image: registry-proxy:local
    build:
      context: ./build/registry-proxy
    environment:
      ALLOW_PUSH: 'true'
      ENABLE_MANIFEST_CACHE: 'true'
      MANIFEST_CACHE_PRIMARY_REGEX: '(stable|nightly|production|test)'
      MANIFEST_CACHE_PRIMARY_TIME: 12h
      MANIFEST_CACHE_SECONDARY_REGEX: '(.*)(\d|\.)+(.*)(\d|\.)+(.*)(\d|\.)+'
      MANIFEST_CACHE_SECONDARY_TIME: 1d
      MANIFEST_CACHE_DEFAULT_TIME: 2s
      CACHE_MAX_SIZE: 20g
      REGISTRIES: "k8s.gcr.io gcr.io us.gcr.io quay.io ghcr.io ${GITLAB_SELFHOSTED_PRIVATE__FQDN} ${GITLAB_SELFHOSTED_PUBLIC__FQDN}"
      AUTH_REGISTRIES: "${GITLAB_SELFHOSTED_PRIVATE__FQDN}:${GITLAB_SELFHOSTED_PRIVATE__USERNAME}:${GITLAB_SELFHOSTED_PRIVATE__PASSWORD}"
      SEND_TIMEOUT: 180s
      CLIENT_BODY_TIMEOUT: 180s
      CLIENT_HEADER_TIMEOUT: 180s
      KEEPALIVE_TIMEOUT: 300s
      PROXY_READ_TIMEOUT: 180s
      PROXY_CONNECT_TIMEOUT: 180s
      PROXY_SEND_TIMEOUT: 180s
      PROXY_CONNECT_READ_TIMEOUT: 180s
      PROXY_CONNECT_CONNECT_TIMEOUT: 180s
      PROXY_CONNECT_SEND_TIMEOUT: 180s
      LISTEN_ADDR: ${REGISTRY_PROXY__LISTEN_ADDR}
      LISTEN_PORT: ${REGISTRY_PROXY__LISTEN_PORT}
    volumes:
      - registry-proxy-cache:/docker_mirror_cache
      - ./ca:/ca
      - ${GITLAB_SELFHOSTED__CA_CHAINS_DIRECTORY}:/usr/local/share/ca-certificates:ro
    healthcheck:
      test: wget -q --spider http://${REGISTRY_PROXY__LISTEN_ADDR}:${REGISTRY_PROXY__LISTEN_PORT}
      interval: 15s
      timeout: 3s
      retries: 2
      start_period: 2s

  all-proxy:
    <<: *common
    image: all-proxy:local
    build:
      context: ./build/all-proxy
    environment:
      LISTEN_ADDR: ${ALL_PROXY__LISTEN_ADDR}
      LISTEN_PORT: ${ALL_PROXY__LISTEN_PORT}
    volumes:
      - all-proxy-cache:/var/cache/squid
      - ./ca:/ca:ro
      - ${ALL_PROXY__CA_CHAINS_DIRECTORY}:/usr/local/share/ca-certificates:ro
    depends_on:
      # need to wait CA cert generation in registry-proxy service
      registry-proxy:
        condition: service_healthy

  non-cache-proxy:
    <<: *common
    image: non-cache-proxy:local
    build:
      context: ./build/non-cache-proxy
    environment:
      LISTEN_ADDR: ${NON_CACHE_PROXY__LISTEN_ADDR}
      LISTEN_PORT: ${NON_CACHE_PROXY__LISTEN_PORT}

volumes:
  registry-proxy-cache:
  all-proxy-cache:
